### ISSUE TITLE
Viewer MXD Updates for New Prod

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Viewer#377]
### File Paths
Viewer MXDs - V:_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers
MXD for https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/335 - \deldot-prod-ags\C:\Projects\DelDOT_NPDES_Reports\mxds\WQIprod.mxd
 
### Updates

- [ ] @cstevenson1 has everything been added for https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/300 ? Also, this issue appears to cover #247. 

- [ ] @cstevenson1 please test and confirm https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/344

- [ ] @cstevenson1 please update symbology for underdrain conveyances and underdrain pipe end structures. 

- [ ] @KCI-Ablowers to update MXD for #335 and pass off to @gerrykelly. 

- [ ] @kanglu666 Will MXD updates handle the changes made here - https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/issues/361 for the field tool? I noticed that "outfall drainage area" and "outfall drainage area labels" still appear in the TOC --> NPDES group. 

- [ ] @KCI-Ablowers to look into https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/58 and update as needed. Will need to track down the most recent PDFs (I believe) and recreate. 

### Republishing
Once this issue is closed, I will create an issue for @kanglu666 to go ahead and republish the services for the new dev viewer for testing.

**Comment by kanglu666** [comment]
MXDs for viewer (new dev server):
V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers

**Comment by cstevenson1** [comment]
@KCI-Ablowers I'm a little confused by this bug. Are we updating base data MXDs or the NPDES data MXDs? Also, the pathway you provided contains MXDs that were saved in a newer version and I cannot open.

**Comment by KCI-Ablowers** [comment]
V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Base_Data_Viewer\BaseData_1_Primary_106.mxd

10.6 Copies of the viewer MXDs - V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers\10_6_Copies

**Comment by cstevenson1** [comment]
@KCI-Ablowers Updated the primary DelDOT view (target_viewer_npdes_101_Label_Option_106) for the NPDES data. Would we be able to test this one before adjusting the rest of the views? 

Some of the edits made were - added underdrain conveyances, added underdrain pipe ends, added structure drainage area, removed outfall drainage areas, grouped labels so they can all be turned off at once.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Talked to Lu and we can publish the MXD above (target_viewer_npdes_101_Label_Option_106) to test the updates/edits. Once published, you will need to test with an account that is a member of the NPDES group.

@kanglu666 Please republish the MXD above - assumed here - V:_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers\10_6_Copies named - target_viewer_npdes_101_Label_Option_106 and reassign to Christina once complete.

**Comment by kanglu666** [comment]
NPDES map service with underdrain has been republished on dev, please test

**Comment by cstevenson1** [comment]
@KCI-Ablowers since the "grouping" cannot easily be implemented, I recommend defaulting "All NPDES Labels" to on and all the individual NPDES label layers (Structures Labels, Conveyances Labels, etc) to off. Otherwise, as it currently sits with the all labels and individual label layers defaulted to on, if the user turns off the "All NPDES Labels" layer, it does nothing because all the individual ones are still one.

![image](https://user-images.githubusercontent.com/16919898/101970305-a79d5900-3bf7-11eb-8318-14557dd3d74e.png)

**Comment by cstevenson1** [comment]
@KCI-Ablowers DelDOT can be removed after the comma but if this is time consuming or will delay the push to prod, then this can probably just be addressed with the next batch of MXD updates.

**Comment by kanglu666** [comment]
fixed, ready for testing in dev

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I can't locate the pdf for the symbology. Can i recreate it using a prod example and the legend from this MXD - V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers\10_6_Copies\target_viewer_npdes_101_Label_Option_106.mxd?

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Scratch the comment above - Lu pointed me to the attached 
[NPDES.pdf](https://github.com/leeensminger/DelDOT-NPDES-Viewer/files/5683502/NPDES.pdf). I will need to recreate this anyway since the formatting needs to be updated.

**Comment by cstevenson1** [comment]
@KCI-Ablowers I think this is good for now. Next time updates are made, may be good to remove underscores from the base map layer names and categorize the drainage areas together. Flowlines and Tax Ditch layer are missing directional arrows.

**Comment by KCI-Ablowers** [comment]
@kanglu666 Use the pdf in the https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/377#issuecomment-743802280 above. Push to prod.

**Comment by cstevenson1** [comment]
@KCI-Ablowers I updated the MXD again per DelDOT's feedback. The PDF legend for the export map function will need to be updated again. 

V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers\10_6_Copies
target_viewer_npdes_101_Label_Option_106

**Comment by KCI-Ablowers** [comment]
Thanks, @cstevenson1. @kanglu666 can you please republish to prod and confirm that the labels are working correctly? I will handle the symbology update and get that to you this evening.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I think we need to update the other MXDs and get those published. While you are updating, please incorporate https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/383. We will need to go back to the NPDES MXD and make this change as well and have @kanglu666 republish.

**Comment by cstevenson1** [comment]
@KCI-Ablowers #383 has been updated.

V:_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers\10_6_Copies

target_viewer_npdes_101_Label_Option_106.mxd

As previously discussed, we were and still are having some issues when sourced to the sde database. If the MXD is sourced to a local copy, such as an extract, the symbology comes through as expected. Please let us know if this is just a known quirk of arcmap and will be fine when published or if we need to change symbology.

**Comment by kanglu666** [comment]
NPDES export legend PDF  has been updated.
Please update all others: 
CDC, NCC, Maintenance, etc

**Comment by cstevenson1** [comment]
@KCI-Ablowers all are not ready yet but the following MXDs are. We will continue to update the thread as more are ready.

V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers

target_viewer_npdes_cnc_06_22_22

**Comment by kanglu666** [comment]
Map services have been updated in dev, ready for testing.

https://devgis.kci.com/arcgis/rest/services/DelDotWebViewer/CNC/MapServer
https://devgis.kci.com/arcgis/rest/services/DelDotWebViewer/NCC/MapServer
https://devgis.kci.com/arcgis/rest/services/DelDotWebViewer/Maintenance/MapServer
https://devgis.kci.com/arcgis/rest/services/DelDotWebViewer/DNREC/MapServer
https://devgis.kci.com/arcgis/rest/services/DelDotWebViewer/NPDES/MapServer
https://devgis.kci.com/arcgis/rest/services/DelDotWebViewer/target_viewer_npdes_Milford/MapServer

**Comment by cstevenson1** [comment]
@KCI-Ablowers minor edits were made to the MXDs listed above and updates were made to the remaining user group MXDs. Please republish all user group MXDs to dev.

**Comment by KCI-Ablowers** [comment]
> @KCI-Ablowers minor edits were made to the MXDs listed above and updates were made to the remaining user group MXDs. Please republish all user group MXDs to dev.

@kanglu666 please republish the MXDs below (pulled from https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/377#issuecomment-1165734065) and the "remaining" user groups (please reach out if you are unclear which need to be republished)

**Comment by kanglu666** [comment]
All MXDs data source re-pointed to dev DB, 
All map services have been republished in dev, ready for testing.

**Comment by cstevenson1** [comment]
@KCI-Ablowers We have reviewed the MXDs and a few are ready for prod, a few need to be republished, and a few are not working as expected but not sure why. Please see break down below. Additionally, once the Status field is ready, I imagine we will need to add a definition query to each MXD to hide the DelDOT BMPs that do not have a status of accepted or construction. If it is almost ready, then we can hold off on pushing to Prod until the definition query has been added.

Push to prod MXDs
1. target_viewer_npdes_cdc_08_01_22
2. target_viewer_npdes_milford_08_01_22
3. target_viewer_npdes_dnrec_08_01_22

Republish MXDs
1. target_viewer_npdes_cnc_08_01_22
2. target_viewer_npdes_elsmere_08_01_22
3. target_viewer_npdes_cod_08_01_22
4. target_viewer_npdes_smyrna_08_01_22
5. target_viewer_npdes_other_08_01_22

The Structure Drainage Area Labels are not working in the dev viewer but appear to be working fine in the MXD for the following:
1. target_npdes_viewer_ncc_08_01_22 
2. target_viewer_maintenance_08_01_22
3. target_viewer_npdes_08_01_22 (additional edits need to be made to this one; was the plan to remove "DelDOT" value for the BMPs symbology?)

**Comment by cstevenson1** [comment]
@KCI-Ablowers I haven't heard back about the labels from my previous comment but we can try republishing to see if that fixes the issues on its own if you'd like. All of the NPDES MXDs are ready to republish as listed below. Once these have been confirmed in Dev, please update the flattened MXD for the service.

V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDot\Dev_mxds\mxds\viewers

target_viewer_npdes_cnc_10_18_22
target_viewer_npdes_cod_10_18_22
target_viewer_npdes_elsmere_10_18_22
target_viewer_npdes_dnrec_10_18_22
target_npdes_viewer_ncc_10_18_22
target_viewer_npdes_10_18_22
target_viewer_npdes_smyrna_10_18_22
target_viewer_npdes_other_10_18_22
target_viewer_npdes_milford_10_18_22
target_viewer_npdes_cdc_10_18_22
target_viewer_maintenance_10_18_22

**Comment by KCI-Ablowers** [comment]
@kanglu666  Please republish the MXDs above - https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/377#issuecomment-1282913756 - to dev and double-check that the data source is pointing to Dev. If not, let me know which one(s). After you get them republished, can you verify that the Structure Drainage Area labels for "target_npdes_viewer_ncc," "target_viewer_maintenance," and "target_viewer_npdes" are drawing correctly? Check out the last section of bullets in this comment - https://github.com/leeensminger/DelDOT-NPDES-Viewer/issues/377#issuecomment-1282913756 - if you need any context. Thanks!!

**Comment by kanglu666** [comment]
all map services have been republished, ready for testing in dev

**Comment by cstevenson1** [comment]
@KCI-Ablowers 

1. Structure Drainage Area labels still aren't working for:
target_npdes_viewer_ncc_10_18_22
target_viewer_maintenance_10_18_22
2. Is the view utilized by the advanced query builder going to align with the map? For example, a definition query was added to the MXD to ensure Design BMPs weren't displayed but they still come up using the query and will highlight on the map. We can discuss options with DelDOT if there's nothing in the notes on what they wanted.
![image](https://user-images.githubusercontent.com/16919898/199979755-74e15602-f2d4-4174-96d2-5f1ef927fd21.png)
3. Do we need to wait to push to prod until the status field is properly updated in prod since the BMP_STATUS field drives a big portion of the BMP layer symbology now?

**Comment by KCI-Ablowers** [comment]
> @KCI-Ablowers
> 
> 1. Structure Drainage Area labels still aren't working for:
>    target_npdes_viewer_ncc_10_18_22
>    target_viewer_maintenance_10_18_22
> 2. Is the view utilized by the advanced query builder going to align with the map? For example, a definition query was added to the MXD to ensure Design BMPs weren't displayed but they still come up using the query and will highlight on the map. We can discuss options with DelDOT if there's nothing in the notes on what they wanted.
>    ![image](https://user-images.githubusercontent.com/16919898/199979755-74e15602-f2d4-4174-96d2-5f1ef927fd21.png)
> 3. Do we need to wait to push to prod until the status field is properly updated in prod since the BMP_STATUS field drives a big portion of the BMP layer symbology now?

1. I will get @kanglu666 to investigate the labels for these. Do you have any queries on the labels in the MXDs @cstevenson1 ?
2. I believe the advanced query builder is against the database, not the contents of the MXD. @kanglu666 can you please confirm?
3. Correct, we will need to wait until DelDOT has the BMP statuses finalized and get the status field populated in Prod before these get published to Prod.

**Comment by kanglu666** [comment]
target_npdes_viewer_ncc_10_18_22
target_viewer_maintenance_10_18_22

Both map services have been republished with the  "Structure Drainage Area labels " updated. ready for testing in dev.

**Comment by KCI-Ablowers** [comment]
> target_npdes_viewer_ncc_10_18_22 target_viewer_maintenance_10_18_22
> 
> Both map services have been republished with the "Structure Drainage Area labels " updated. ready for testing in dev.

@cstevenson1 Please test when you can. Also, I confirmed with Lu that the advanced query builder works against the database and not the data present in the MXD.

**Comment by cstevenson1** [comment]
@KCI-Ablowers the labels are working. Pushing to prod is on-hold until the BMP unifier data is ready
